// src/main/webapp/app/entities/institutional-subscription/delete/institutional-subscription-delete-dialog.component.ts
import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { NgbActiveModal } from '@ng-bootstrap/ng-bootstrap';

import SharedModule from 'app/shared/shared.module';
import { ITEM_DELETED_EVENT } from 'app/config/navigation.constants';
import { IInstitutionalSubscription } from '../institutional-subscription.model';
import { InstitutionalSubscriptionService } from '../service/institutional-subscription.service';

@Component({
  standalone: true,
  templateUrl: './institutional-subscription-delete-dialog.component.html',
  imports: [SharedModule, FormsModule],
})
export class InstitutionalSubscriptionDeleteDialogComponent {
  institutionalSubscription?: IInstitutionalSubscription;

  protected institutionalSubscriptionService = inject(InstitutionalSubscriptionService);
  protected activeModal = inject(NgbActiveModal);

  cancel(): void {
    this.activeModal.dismiss();
  }

  confirmDelete(id: number): void {
    this.institutionalSubscriptionService.delete(id).subscribe(() => {
      this.activeModal.close(ITEM_DELETED_EVENT);
    });
  }
}

@if (institutionalSubscription) {
  <form name="deleteForm" (ngSubmit)="confirmDelete(institutionalSubscription.id!)">
    <div class="modal-header">
      <h4 class="modal-title" data-cy="institutionalSubscriptionDeleteDialogHeading" jhiTranslate="entity.delete.title">
        Confirm delete operation
      </h4>
    </div>

    <div class="modal-body">
      <jhi-alert-error></jhi-alert-error>
      <p
        id="jhi-delete-institutionalSubscription-heading"
        jhiTranslate="calvaryApiGatewayApp.institutionalSubscription.delete.question"
        [translateValues]="{ id: institutionalSubscription.id }"
      >
        Are you sure you want to delete Institutional Subscription {{ institutionalSubscription.id }}?
      </p>
    </div>

    <div class="modal-footer">
      <button type="button" class="btn btn-secondary" data-dismiss="modal" (click)="cancel()">
        <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
      </button>

      <button id="jhi-confirm-delete-institutionalSubscription" data-cy="entityConfirmDeleteButton" type="submit" class="btn btn-danger">
        <fa-icon icon="times"></fa-icon>&nbsp;<span jhiTranslate="entity.action.delete">Delete</span>
      </button>
    </div>
  </form>
}

// src/main/webapp/app/entities/institutional-subscription/institutional-subscription-delete-dialog.tsx
import React, { useEffect, useState } from 'react';
import { useLocation, useNavigate, useParams } from 'react-router-dom';
import { Button, Modal, ModalBody, ModalFooter, ModalHeader } from 'reactstrap';

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { useAppDispatch, useAppSelector } from 'app/config/store';
import { deleteEntity, getEntity } from './institutional-subscription.reducer';

export const InstitutionalSubscriptionDeleteDialog = () => {
  const dispatch = useAppDispatch();

  const pageLocation = useLocation();
  const navigate = useNavigate();
  const { id } = useParams<'id'>();

  const [loadModal, setLoadModal] = useState(false);

  useEffect(() => {
    dispatch(getEntity(id));
    setLoadModal(true);
  }, []);

  const institutionalSubscriptionEntity = useAppSelector(state => state.institutionalSubscription.entity);
  const updateSuccess = useAppSelector(state => state.institutionalSubscription.updateSuccess);

  const handleClose = () => {
    navigate(`/institutional-subscription${pageLocation.search}`);
  };

  useEffect(() => {
    if (updateSuccess && loadModal) {
      handleClose();
      setLoadModal(false);
    }
  }, [updateSuccess]);

  const confirmDelete = () => {
    dispatch(deleteEntity(institutionalSubscriptionEntity.id));
  };

  return (
    <Modal isOpen toggle={handleClose}>
      <ModalHeader toggle={handleClose} data-cy="institutionalSubscriptionDeleteDialogHeading">
        Confirm delete operation
      </ModalHeader>
      <ModalBody id="calvaryErpApiApp.institutionalSubscription.delete.question">
        Are you sure you want to delete Institutional Subscription {institutionalSubscriptionEntity.id}?
      </ModalBody>
      <ModalFooter>
        <Button color="secondary" onClick={handleClose}>
          <FontAwesomeIcon icon="ban" />
          &nbsp; Cancel
        </Button>
        <Button
          id="jhi-confirm-delete-institutionalSubscription"
          data-cy="entityConfirmDeleteButton"
          color="danger"
          onClick={confirmDelete}
        >
          <FontAwesomeIcon icon="trash" />
          &nbsp; Delete
        </Button>
      </ModalFooter>
    </Modal>
  );
};

export default InstitutionalSubscriptionDeleteDialog;
