// src/main/webapp/app/entities/institutional-subscription/institutional-subscription-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Col, Row } from 'reactstrap';
import { TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './institutional-subscription.reducer';

export const InstitutionalSubscriptionDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const institutionalSubscriptionEntity = useAppSelector(state => state.institutionalSubscription.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="institutionalSubscriptionDetailsHeading">Institutional Subscription</h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">ID</span>
          </dt>
          <dd>{institutionalSubscriptionEntity.id}</dd>
          <dt>
            <span id="startDate">Start Date</span>
          </dt>
          <dd>
            {institutionalSubscriptionEntity.startDate ? (
              <TextFormat value={institutionalSubscriptionEntity.startDate} type="date" format={APP_LOCAL_DATE_FORMAT} />
            ) : null}
          </dd>
          <dt>
            <span id="expiryDate">Expiry Date</span>
          </dt>
          <dd>
            {institutionalSubscriptionEntity.expiryDate ? (
              <TextFormat value={institutionalSubscriptionEntity.expiryDate} type="date" format={APP_LOCAL_DATE_FORMAT} />
            ) : null}
          </dd>
          <dt>
            <span id="memberLimit">Member Limit</span>
          </dt>
          <dd>{institutionalSubscriptionEntity.memberLimit}</dd>
          <dt>Institution</dt>
          <dd>{institutionalSubscriptionEntity.institution ? institutionalSubscriptionEntity.institution.institutionName : ''}</dd>
        </dl>
        <Button tag={Link} to="/institutional-subscription" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" /> <span className="d-none d-md-inline">Back</span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/institutional-subscription/${institutionalSubscriptionEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
        </Button>
      </Col>
    </Row>
  );
};

export default InstitutionalSubscriptionDetail;

// src/main/webapp/app/entities/institutional-subscription/detail/institutional-subscription-detail.component.ts
import { Component, input } from '@angular/core';
import { RouterModule } from '@angular/router';

import SharedModule from 'app/shared/shared.module';
import { DurationPipe, FormatMediumDatePipe, FormatMediumDatetimePipe } from 'app/shared/date';
import { IInstitutionalSubscription } from '../institutional-subscription.model';

@Component({
  standalone: true,
  selector: 'jhi-institutional-subscription-detail',
  templateUrl: './institutional-subscription-detail.component.html',
  imports: [SharedModule, RouterModule, DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe],
})
export class InstitutionalSubscriptionDetailComponent {
  institutionalSubscription = input<IInstitutionalSubscription | null>(null);

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    @if (institutionalSubscription(); as institutionalSubscriptionRef) {
      <div>
        <h2 data-cy="institutionalSubscriptionDetailsHeading">
          <span jhiTranslate="calvaryApiGatewayApp.institutionalSubscription.detail.title">Institutional Subscription</span>
        </h2>

        <hr />

        <jhi-alert-error></jhi-alert-error>

        <jhi-alert></jhi-alert>

        <dl class="row-md jh-entity-details">
          <dt><span jhiTranslate="global.field.id">ID</span></dt>
          <dd>
            <span>{{ institutionalSubscriptionRef.id }}</span>
          </dd>
          <dt><span jhiTranslate="calvaryApiGatewayApp.institutionalSubscription.startDate">Start Date</span></dt>
          <dd>
            <span>{{ institutionalSubscriptionRef.startDate | formatMediumDate }}</span>
          </dd>
          <dt><span jhiTranslate="calvaryApiGatewayApp.institutionalSubscription.expiryDate">Expiry Date</span></dt>
          <dd>
            <span>{{ institutionalSubscriptionRef.expiryDate | formatMediumDate }}</span>
          </dd>
          <dt><span jhiTranslate="calvaryApiGatewayApp.institutionalSubscription.memberLimit">Member Limit</span></dt>
          <dd>
            <span>{{ institutionalSubscriptionRef.memberLimit }}</span>
          </dd>
          <dt><span jhiTranslate="calvaryApiGatewayApp.institutionalSubscription.institution">Institution</span></dt>
          <dd>
            @if (institutionalSubscription()!.institution) {
              <div>
                <a [routerLink]="['/institution', institutionalSubscription()!.institution?.id, 'view']">{{
                  institutionalSubscriptionRef.institution?.institutionName
                }}</a>
              </div>
            }
          </dd>
        </dl>

        <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
          <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
        </button>

        <button
          type="button"
          [routerLink]="['/institutional-subscription', institutionalSubscriptionRef.id, 'edit']"
          class="btn btn-primary"
        >
          <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
        </button>
      </div>
    }
  </div>
</div>
